### ISSUE TITLE
Error on Death

### ISSUE THREAD

**Issue by Drackrath** [Echological/Lifesteal-MH#1]
```
[15:26:49 ERROR]: Could not pass event PlayerDeathEvent to Lifesteal v7.0.0
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "page.echology.lifesteal.config.Config.value(java.lang.Class)" is null
        at page.echology.lifesteal.utility.DeathHandle.other(DeathHandle.java:100) ~[Lifesteal.jar:?]
        at page.echology.lifesteal.event.Listen.death(Listen.java:29) ~[Lifesteal.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor54.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-174]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:905) ~[paper-1.19.2.jar:git-Paper-174]
        at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:862) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1475) ~[?:?]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:982) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1025) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.causeFallDamage(LivingEntity.java:1949) ~[?:?]
        at net.minecraft.world.entity.player.Player.causeFallDamage(Player.java:1777) ~[?:?]
        at net.minecraft.world.level.block.Block.fallOn(Block.java:462) ~[paper-1.19.2.jar:git-Paper-174]
        at net.minecraft.world.entity.Entity.checkFallDamage(Entity.java:1622) ~[paper-1.19.2.jar:git-Paper-174]
        at net.minecraft.world.entity.LivingEntity.checkFallDamage(LivingEntity.java:371) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.doCheckFallDamage(ServerPlayer.java:1461) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1633) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:29) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos.handle(ServerboundMovePlayerPacket.java:66) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-174]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-174]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-174]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-174]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-174]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1445) ~[paper-1.19.2.jar:git-Paper-174]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-174]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-174]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Setloth** [comment]
Could you attach a copy of your config.yml file so I could take a look?

**Comment by Setloth** [comment]
Nevermind, I think I found the issue

**Comment by Setloth** [comment]
Can you confirm if this issue is fixed?
